title: Nathaneul Benioff # your name (or website title) here
logo: "eyJidWNrZXQiOiJtaWxlc3BsaXQiLCJrZXkiOiJwaG90b3NcLzQ1MzE0XC9ub3JtYWxcLzI0NzIxMTAxIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjo2MjAsImZpdCI6ImNvdmVyIiwicG9zaXRpb24iOiJjZW50ZXIifX19.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 coffeepaws 
  <br><br>
  Student and avid runner
  <br><br>
  <a href="https://www.linkedin.com/in/nathaneul-benioff-62ba15165/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
